---
# Настройка SSH и добавление ключей
- name: Show debug message
  debug:
    msg: "Deploying SSH keys for {{ inventory_hostname }}"

- name: Ensure SSH directory exists
  ansible.builtin.file:
    path: "~{{ target_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  become: yes

# Добавляем ключи из директории public_keys ( юзера можно определить переменной)
- name: Add authorized keys from public_keys directory
  ansible.posix.authorized_key:
    user: "{{ target_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ ssh_keys_public_dir }}/*.pub"
  become: yes
    
# удаляем ключи совпадающие с ключами из директории revoked
- name: Remove revoked keys
  ansible.posix.authorized_key:
    user: "{{ target_user }}"
    state: absent
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ ssh_keys_revoked_dir }}/*.pub"
  become: yes

- name: Set PermitRootLogin to prohibit-password
  ansible.builtin.lineinfile:
    path: "{{ sshd_config }}"
    regexp: '^#?\s*PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
    state: present
  become: yes

- name: Validate SSH configuration
  ansible.builtin.command: sshd -t -f "{{ sshd_config }}"
  register: sshd_validation
  changed_when: false
  become: yes
  notify: Restart SSH

- name: Restart SSH service
  ansible.builtin.service:
    name: "{{ ssh_service }}"
    state: restarted
  become: yes
  tags: [never, restart] 